import { useEffect, useRef } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { ModelConfig } from '@/components/ModelSettingsModal';

interface UseAutoGenerateSummaryParams {
  shouldAutoGenerate: boolean;
  meetingId: string;
  folderPath?: string | null;
  /** Loaded transcript count — arriving pages re-arm the one-shot check (WS7.3). */
  transcriptCount: number;
  modelConfig: ModelConfig;
  generateSummary: (customPrompt: string) => Promise<void>;
  onAutoGenerateComplete?: () => void;
}

/**
 * Auto-generate a summary when the flag is set. specs/0029 WS7.3: transcripts can
 * populate a beat AFTER the flag flips (async paginated load), so the transcript count
 * is a dependency — the effect re-checks when transcripts arrive instead of silently
 * missing the one-shot window. A per-meeting ref keeps generation once-only per visit
 * even as later transcript pages re-run the effect.
 */
export function useAutoGenerateSummary({
  shouldAutoGenerate,
  meetingId,
  folderPath,
  transcriptCount,
  modelConfig,
  generateSummary,
  onAutoGenerateComplete,
}: UseAutoGenerateSummaryParams): void {
  const hasAutoGeneratedRef = useRef(false);
  useEffect(() => {
    hasAutoGeneratedRef.current = false;
  }, [meetingId]);

  useEffect(() => {
    let cancelled = false;

    const autoGenerate = async () => {
      if (!shouldAutoGenerate || hasAutoGeneratedRef.current || cancelled) return;
      if (transcriptCount === 0) {
        // specs/0029 WS7.2 x WS7.3: a record-only meeting NEVER gets transcripts
        // pushed here (there was no live STT) — waiting would starve auto-summary
        // forever. If audio awaits deferred transcription, proceed:
        // handleGenerateSummary transcribes first, then summarizes. Otherwise keep
        // waiting for the async paginated load as before.
        let audioAwaiting = false;
        try {
          audioAwaiting = folderPath
            ? await invoke<boolean>('api_meeting_audio_available', { meetingId })
            : false;
        } catch (error) {
          console.warn('Could not check audio availability for auto-summary:', error);
        }
        if (cancelled) return;
        if (!audioAwaiting) {
          console.log('🤖 Auto-generate armed but transcripts not loaded yet — waiting');
          return; // re-runs via the transcript-count dependency
        }
        console.log('🤖 Record-only meeting — auto-summary will transcribe first (WS7.2)');
      }

      hasAutoGeneratedRef.current = true;
      console.log(`🤖 Auto-generating summary with ${modelConfig.provider}/${modelConfig.model}...`);
      await generateSummary('');

      // Notify parent that auto-generation is complete (only if not cancelled)
      if (onAutoGenerateComplete && !cancelled) {
        onAutoGenerateComplete();
      }
    };

    autoGenerate();

    // Cleanup: cancel if component unmounts or meeting changes
    return () => {
      cancelled = true;
    };
  }, [shouldAutoGenerate, meetingId, transcriptCount]); // Re-run if meeting or transcripts change
}
