"use client";

import { Transcript, TranscriptSegmentData, MeetingSpeaker } from '@/types';
import {
  VirtualizedTranscriptView,
  type InlineSpeakerAssignment,
} from '@/components/VirtualizedTranscriptView';
import { TranscriptButtonGroup } from './TranscriptButtonGroup';
import { SpeakerFilterChip } from './SpeakerFilterChip';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { toast } from 'sonner';
import { AlertCircle, Loader2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { UseSpeakersReturn } from '@/hooks/useSpeakers';
import { useBacklog } from '@/contexts/DeferredBacklogProvider';
import { isUnprocessedRecording } from '@/lib/processing-mode';
import { isMeetingInFlight } from '@/lib/deferred-backlog';
import { buildSpeakerPhotoMap } from '@/lib/speaker-photos';
import {
  AUDIO_FAILED_NOTE,
  canTranscribe,
  useMeetingAudioStatus,
} from '@/hooks/useMeetingAudioStatus';

interface TranscriptPanelProps {
  transcripts: Transcript[];
  onCopyTranscript: () => void;
  onOpenMeetingFolder: () => Promise<void>;
  isRecording: boolean;
  disableAutoScroll?: boolean;

  // Optional pagination props (when using virtualization)
  usePagination?: boolean;
  segments?: TranscriptSegmentData[];
  hasMore?: boolean;
  isLoadingMore?: boolean;
  totalCount?: number;
  loadedCount?: number;
  onLoadMore?: () => void;

  // Retranscription props
  meetingId?: string;
  meetingFolderPath?: string | null;
  onRefetchTranscripts?: () => Promise<void>;

  /** The shared speaker controller (specs/0019 WS2.1), owned by the page since
   *  specs/0057 Plan 3 — the channel strip moved above the tabs, so the legend and
   *  this panel's inline assignment both read one page-level source of truth. */
  speakersController: UseSpeakersReturn;

  /** specs/0033 — search deep-link: scroll to this segment once it's loaded.
   *  Best-effort; a stale id (regenerated by "Transcribe now") silently no-ops. */
  scrollToSegmentId?: string;
  /** specs/0033 — whether the panel is actually visible (the meeting-details tabpanel
   *  is kept mounted display:none; a hidden subtree can't be scrolled). */
  isScrollTargetVisible?: boolean;
  /** specs/0033 — the deep-link scroll ran (or was abandoned): consume the intent. */
  onScrollToSegmentDone?: () => void;

  /** specs/0061 W4 (task 3) — a speaker key clicked in the channel strip; when set,
   *  only that speaker's segments render, above a "Showing: <name>" chip. This is the
   *  group's PRIMARY key, used only to resolve the chip's display name — see
   *  `speakerFilterKeys` for which segments actually match. */
  speakerFilter?: string | null;
  /** specs/0061 W4 task 3, ruling R36 — every member key of the selected consolidated
   *  speaker group (a group can span several raw diarization keys mapped to the same
   *  Person). A segment renders when its `speaker` is ANY of these. Falls back to
   *  `[speakerFilter]` when omitted, so a caller with no consolidation concept (e.g. a
   *  single ungrouped key) can pass just `speakerFilter`. */
  speakerFilterKeys?: string[] | null;
  /** Clear the filter (the chip's own "Clear speaker filter" button). */
  onClearSpeakerFilter?: () => void;

  /**
   * Override the root container classes. Defaults to the standalone side-panel layout
   * (fixed width + right border). Pass e.g. `"flex w-full flex-col"` when embedding the panel
   * inside a tab that already owns the width (meeting-details right sidebar).
   */
  className?: string;
}

export function TranscriptPanel({
  transcripts,
  onCopyTranscript,
  onOpenMeetingFolder,
  isRecording,
  disableAutoScroll = false,
  usePagination = false,
  segments,
  hasMore,
  isLoadingMore,
  totalCount,
  loadedCount,
  onLoadMore,
  meetingId,
  meetingFolderPath,
  onRefetchTranscripts,
  speakersController,
  scrollToSegmentId,
  isScrollTargetVisible = true,
  onScrollToSegmentDone,
  speakerFilter,
  speakerFilterKeys,
  onClearSpeakerFilter,
  className = 'hidden md:flex md:w-1/4 lg:w-1/3 min-w-0 border-r border-border bg-card flex-col relative shrink-0',
}: TranscriptPanelProps) {
  // specs/0045 WS4 — mirrors the probes in TranscriptButtonGroup (same cheap IPC reads)
  // so this panel can independently drive the "unprocessed recording" transcript empty
  // state. Not lifted/shared: TranscriptButtonGroup's existing test coverage assumes it
  // self-probes, so duplicating here is the smaller, lower-risk change (see task-9-report).
  const [processingMode, setProcessingMode] = useState<string | null>(null);
  useEffect(() => {
    setProcessingMode(null);
    if (!meetingId) return;
    let cancelled = false;
    invoke<string | null>('api_get_meeting_processing_mode', { meetingId })
      .then((mode) => {
        if (!cancelled) setProcessingMode(mode);
      })
      .catch((error) => {
        console.warn('Failed to check meeting processing mode:', error);
      });
    return () => {
      cancelled = true;
    };
  }, [meetingId]);

  // specs/0072 W3 — follows `meeting-audio-state-changed`, so a failed identification or
  // a purge shows here without a refetch.
  const audio = useMeetingAudioStatus(meetingId);
  const audioAvailable = audio ? canTranscribe(audio) : null;

  const { view: backlogView, enqueueMeeting } = useBacklog();

  // specs/0071 W3 — is THIS meeting being processed right now?
  //
  // The reported symptom was 3 min 19 s of silence after pressing stop. The work was
  // running and the stop path had already handed it to this same controller — but the page
  // the user lands on said nothing, so the only visible state was a stale transcript with no
  // hint that a better one was coming. The sidebar queue knew; the meeting did not. This file
  // was already importing `useBacklog` and using only `enqueueMeeting`.
  const isProcessingThisMeeting = isMeetingInFlight(backlogView.items, meetingId);
  const backlogStage = meetingId
    ? (backlogView.items.find((i) => i.meeting.id === meetingId)?.status ?? null)
    : null;

  // specs/0041 WS7.2 — post-correction reconciliation. The view has already applied an
  // optimistic overlay (the server result is deterministic), so the transcript refetch
  // and legend refresh run in the BACKGROUND: never awaited by the correction path, and
  // the refetch contract (usePaginatedTranscripts.refetch) preserves the pagination
  // window + scroll position, so the reader's viewport stays put.
  const reconcileInBackground = useCallback(() => {
    void Promise.resolve(onRefetchTranscripts?.()).catch((error) => {
      console.error('Background transcript refetch failed:', error);
    });
    void speakersController.refresh().catch((error) => {
      console.error('Background speaker refresh failed:', error);
    });
  }, [onRefetchTranscripts, speakersController]);

  // specs/0019 WS2.3 — move one transcript line to another speaker (the per-segment
  // "split"). Sticky via api_set_segment_speaker. Returns success so the view can keep
  // or revert its optimistic overlay (specs/0041 WS7.2).
  const reassignSegment = useCallback(
    async (transcriptId: string, speakerKey: string): Promise<boolean> => {
      if (!meetingId) return false;
      try {
        await invoke('api_set_segment_speaker', { meetingId, transcriptId, speakerKey });
        reconcileInBackground();
        return true;
      } catch (error) {
        console.error('Failed to reassign segment speaker:', error);
        toast.error('Could not move this line', {
          description: error instanceof Error ? error.message : String(error),
        });
        return false;
      }
    },
    [meetingId, reconcileInBackground],
  );

  // specs/0039 WS2 — bulk span reassignment: move a contiguous run of lines to one
  // existing speaker in a single write. Sticky via api_set_segment_speakers (the batched
  // form of the per-line override), so it survives re-diarization exactly like the
  // single-line path. Returns success so the view can keep/revert its optimistic
  // overlay; reconciliation is background-only (specs/0041 WS7.2 — no scroll reset).
  const reassignSegments = useCallback(
    async (transcriptIds: string[], speakerKey: string): Promise<boolean> => {
      if (!meetingId || transcriptIds.length === 0) return false;
      try {
        await invoke('api_set_segment_speakers', {
          meetingId,
          transcriptIds,
          speakerKey,
        });
        reconcileInBackground();
        return true;
      } catch (error) {
        console.error('Failed to reassign segment span:', error);
        toast.error('Could not reassign these lines', {
          description: error instanceof Error ? error.message : String(error),
        });
        return false;
      }
    },
    [meetingId, reconcileInBackground],
  );

  // specs/0039 WS2 — mint a brand-new speaker the clusterer missed, so a mis-attributed
  // span can be moved to a fourth (etc.) identity. The returned `manual_<uuid>` key has
  // no embedding, so it's inert for voiceprint enrollment — a plain reassignment target.
  const createSpeaker = useCallback(
    async (
      displayName: string,
    ): Promise<{ speakerKey: string; displayName: string } | null> => {
      if (!meetingId) return null;
      const trimmed = displayName.trim();
      if (!trimmed) return null;
      try {
        const dto = await invoke<MeetingSpeaker>('api_create_meeting_speaker', {
          meetingId,
          displayName: trimmed,
        });
        // Refresh the speaker list so the new speaker appears in the legend + menus.
        await speakersController.refresh();
        return { speakerKey: dto.speakerKey, displayName: dto.displayName };
      } catch (error) {
        console.error('Failed to create meeting speaker:', error);
        toast.error('Could not create speaker', {
          description: error instanceof Error ? error.message : String(error),
        });
        return null;
      }
    },
    [meetingId, speakersController],
  );

  // specs/0061 W5 (task 5) — save a manually corrected line's text. Sticky via
  // api_set_segment_text (trims, rejects empty, flags user_edited so the Enhance
  // dialog can warn before a re-transcribe would discard it). Returns success so the
  // view can keep/revert its optimistic overlay (same contract as reassignSegment);
  // reconciliation is background-only (specs/0041 WS7.2 — no scroll reset).
  const editSegmentText = useCallback(
    async (transcriptId: string, text: string): Promise<boolean> => {
      if (!meetingId) return false;
      try {
        await invoke('api_set_segment_text', { meetingId, transcriptId, text });
        reconcileInBackground();
        return true;
      } catch (error) {
        console.error('Failed to save edited segment text:', error);
        toast.error('Could not save this edit', {
          description: error instanceof Error ? error.message : String(error),
        });
        return false;
      }
    },
    [meetingId, reconcileInBackground],
  );

  // Directory photos for the run-header avatars — resolved once per view from the
  // controller's already-loaded speakers/attendees/people, never per row.
  const speakerPhotos = useMemo(
    () =>
      buildSpeakerPhotoMap(
        speakersController.speakers,
        speakersController.attendees,
        speakersController.people,
      ),
    [speakersController.speakers, speakersController.attendees, speakersController.people],
  );

  // Inline assignment wiring for the transcript — only when viewing (not recording)
  // and the meeting has a speaker directory to pick from. Absent => names are static.
  const inlineAssignment: InlineSpeakerAssignment | undefined = useMemo(() => {
    if (isRecording || !meetingId) return undefined;
    const speakerOptions = speakersController.speakers.map((s) => ({
      speakerKey: s.speakerKey,
      displayName: s.displayName,
    }));
    // specs/0061 W4 (task 2) — the owner's `local` speakers row may not exist yet
    // (ensure_local_speaker only upserts it once something is actually reassigned to
    // them), but reassigning TO them always works. Offer "You" as a menu target up
    // front so the owner isn't stuck fighting a menu that doesn't list them; skip the
    // injection when a real `local` row is already present, so it isn't listed twice.
    const speakers = speakerOptions.some((s) => s.speakerKey === 'local')
      ? speakerOptions
      : [{ speakerKey: 'local', displayName: 'You' }, ...speakerOptions];
    return {
      attendees: speakersController.attendees,
      people: speakersController.people,
      onAssignAttendee: speakersController.assignAttendee,
      onAssignPerson: speakersController.assignPerson,
      speakers,
      onReassignSegment: reassignSegment,
      onReassignSegments: reassignSegments,
      onCreateSpeaker: createSpeaker,
      speakerPhotos,
    };
  }, [
    speakerPhotos,
    isRecording,
    meetingId,
    speakersController.attendees,
    speakersController.people,
    speakersController.assignAttendee,
    speakersController.assignPerson,
    speakersController.speakers,
    reassignSegment,
    reassignSegments,
    createSpeaker,
  ]);

  // Convert transcripts to segments if pagination is not used but we want virtualization
  const allSegments = useMemo(() => {
    if (usePagination && segments) {
      return segments;
    }
    // Convert transcripts to segments for virtualization
    return transcripts.map(t => ({
      id: t.id,
      timestamp: t.audio_start_time ?? 0,
      endTime: t.audio_end_time,
      text: t.text,
      confidence: t.confidence,
      speaker: t.speaker,
      speakerName: t.speaker_name,
      userEdited: t.user_edited,
    }));
  }, [transcripts, usePagination, segments]);

  // specs/0061 W4 (task 3), ruling R36 — filter to just the selected group's lines.
  // Matches ANY member key (a consolidated group can span several raw diarization
  // keys), not only the primary — a single-key caller can just pass `speakerFilter`
  // and rely on the fallback. Talk-time totals (useMeetingTalkTime, in SpeakerLegend)
  // read the whole meeting separately and are unaffected by this view-local filter.
  const effectiveFilterKeys = useMemo(
    () => speakerFilterKeys ?? (speakerFilter ? [speakerFilter] : null),
    [speakerFilterKeys, speakerFilter],
  );
  const convertedSegments = useMemo(() => {
    if (!effectiveFilterKeys) return allSegments;
    return allSegments.filter((s) => !!s.speaker && effectiveFilterKeys.includes(s.speaker));
  }, [allSegments, effectiveFilterKeys]);

  // The filter chip's label — resolve the clicked key against the speaker
  // directory so it reads a real name ("Tomas"); fall back to the raw key in the
  // (should-not-happen) case nothing matches.
  const speakerFilterName = useMemo(() => {
    if (!speakerFilter) return null;
    return (
      speakersController.speakers.find((s) => s.speakerKey === speakerFilter)?.displayName ??
      speakerFilter
    );
  }, [speakerFilter, speakersController.speakers]);

  // specs/0045 WS4 — a finished-but-unprocessed deferred recording: audio on disk,
  // still marked deferred, and no transcript segments loaded yet. Drives the
  // "hasn't been processed yet" transcript empty state instead of the generic
  // welcome copy. Gated to !isRecording below — meaningless mid-recording.
  //
  // specs/0061 review, I3 — this MUST read the unfiltered `allSegments`, not the
  // speaker-filtered `convertedSegments`: whether the meeting has transcripts at all
  // is unrelated to which speaker filter chip happens to be active. A meeting still
  // marked `defer` (the backlog only clears that marker after transcribe + diarize +
  // summarize ALL succeed, so a failed summarize leaves it set) that genuinely has
  // loaded transcripts must never flip into "hasn't been processed yet" just because
  // the active speaker filter matches zero of them — that state's "Process now"
  // affordance routes to `replace_meeting_transcripts`, which deletes every
  // transcript row (including user edits) with no warning.
  const unprocessed = isUnprocessedRecording({
    hasTranscripts: allSegments.length > 0,
    isDeferred: processingMode === 'defer',
    audioAvailable: audioAvailable === true,
  });

  const handleProcessNow = useCallback(() => {
    if (!meetingId) return;
    enqueueMeeting(meetingId, { force: true });
  }, [meetingId, enqueueMeeting]);

  return (
    <div className={cn(className)}>
      {/* Control area — sits tight under the document tabs. */}
      <div className="pb-3 border-b border-border">
        {/* specs/0061 review, I3 — transcriptCount below is the unfiltered count:
            it drives "Copy Transcript" disabled state, the sparse-transcript
            warning, and the diarize button, none of which should react to the
            view-local speaker filter. `totalCount` (paginated) is already
            meeting-wide; the non-paginated branch already reads raw
            `transcripts`, so only this fallback needed correcting from the
            filtered `convertedSegments`. */}
        <TranscriptButtonGroup
          transcriptCount={usePagination ? (totalCount ?? allSegments.length) : (transcripts?.length || 0)}
          onCopyTranscript={onCopyTranscript}
          onOpenMeetingFolder={onOpenMeetingFolder}
          meetingId={meetingId}
          meetingFolderPath={meetingFolderPath}
          onRefetchTranscripts={onRefetchTranscripts}
        />
      </div>

      {/* specs/0071 W3 — this meeting is being processed right now. Stopping a meeting that
          was deferred at any point queues a full repass (retranscribe, then summarize), which
          on a short recording still took over three minutes — and nothing on this page said
          so, so the stale transcript below looked like the final answer. */}
      {isProcessingThisMeeting && (
        <div
          role="status"
          className="mt-2 flex items-center gap-2 rounded-[3px] border border-brand/30 bg-brand/5 px-3 py-2"
        >
          <Loader2 size={14} aria-hidden="true" className="animate-spin text-brand" />
          <p className="text-xs text-foreground">
            {backlogStage === 'waiting'
              ? 'Queued for processing — the transcript and summary will update when it runs.'
              : backlogStage === 'summarizing'
                ? 'Summarizing this meeting…'
                : 'Re-transcribing this meeting — the transcript below will update when it finishes.'}
          </p>
        </div>
      )}

      {/* specs/0072 W3 — speaker identification failed; the audio stays for a retry (the
          activity queue's Retry, or Identify speakers above). */}
      {!isRecording && audio?.state === 'failed' && (
        <div
          role="status"
          className="mt-2 flex items-center gap-2 rounded-[3px] border border-border bg-muted/40 px-3 py-2"
        >
          <AlertCircle size={14} aria-hidden="true" className="shrink-0 text-muted-foreground" />
          <p className="text-xs text-muted-foreground">{AUDIO_FAILED_NOTE}</p>
        </div>
      )}

      {/* specs/0061 W4 (task 3) — filter chip, above the list, only while filtered. */}
      {speakerFilterName && (
        <div className="pt-2">
          <SpeakerFilterChip displayName={speakerFilterName} onClear={onClearSpeakerFilter} />
        </div>
      )}

      {/* Transcript content - use virtualized view for better performance. `overflow-clip`,
          not `overflow-hidden`: hidden makes this div a scroll container, which would pin the
          selection bar's `sticky` to it instead of to the page column that actually scrolls. */}
      <div className="flex-1 overflow-clip pb-4">
        <VirtualizedTranscriptView
          segments={convertedSegments}
          isRecording={isRecording}
          isPaused={false}
          isProcessing={false}
          isStopping={false}
          enableStreaming={false}
          showConfidence={true}
          disableAutoScroll={disableAutoScroll}
          hasMore={hasMore}
          isLoadingMore={isLoadingMore}
          totalCount={totalCount}
          loadedCount={loadedCount}
          onLoadMore={onLoadMore}
          assignment={inlineAssignment}
          scrollToSegmentId={scrollToSegmentId}
          scrollTargetVisible={isScrollTargetVisible}
          onScrollToSegmentDone={onScrollToSegmentDone}
          unprocessed={!isRecording && unprocessed}
          onProcessNow={meetingId ? handleProcessNow : undefined}
          onEditText={!isRecording && meetingId ? editSegmentText : undefined}
        />
      </div>
    </div>
  );
}
