// build-mock.mjs — generate scripts/shots/tauri-mock.js from src-tauri/fixtures/demo
// (specs/0059 Task 10). Run: node scripts/shots/build-mock.mjs (or `pnpm shots:mock`).
//
// Why generated instead of hand-written: the fixture dataset (src-tauri/fixtures/demo/)
// is the single source of truth for demo content (people, meetings, transcripts,
// summaries, action items — specs/0059 Task 2). Hand-maintaining a second copy of that
// data in tauri-mock.js would drift the moment the fixtures change. This script reads
// the fixture JSON and emits a tauri-mock.js whose FIXTURES are derived from it, so
// regenerating after a fixture edit is `node scripts/shots/build-mock.mjs`.
//
// Command shapes below are copied from the real Tauri command signatures
// (src-tauri/src/*/commands.rs, *view.rs, database/models.rs, repositories/*.rs) and
// their frontend callers (grepped `invoke(` under src/) — NOT guessed. See the
// per-command comments for the source. `src/__tests__/mock-contract.test.ts` fails the
// build if this file ever answers a command name that doesn't exist in registry.rs.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const fx = join(here, '..', '..', 'src-tauri', 'fixtures', 'demo');

const people = JSON.parse(readFileSync(join(fx, 'people.json'), 'utf8'));
const meetings = readdirSync(join(fx, 'meetings'))
  .filter((f) => f.endsWith('.json'))
  .sort()
  .map((f) => JSON.parse(readFileSync(join(fx, 'meetings', f), 'utf8')));

// No timestamp/generation-time value is baked into the header below: this output must
// be byte-identical across repeated runs against the same fixtures, so a regeneration
// with no fixture changes produces an empty `git diff` (rather than churn on every run).
const body = `// GENERATED by scripts/shots/build-mock.mjs from src-tauri/fixtures/demo — do not edit.
// Regenerate with: node scripts/shots/build-mock.mjs (or \`pnpm shots:mock\`).
// ${meetings.length} meetings, ${people.length} people.
//
// Browser-side stub of the Tauri v2 runtime, injected BEFORE the app boots (via CDP
// Page.addScriptToEvaluateOnNewDocument) so the Next app can run in plain headless
// Chrome for screenshots. Without this, the providers call invoke(...), get no Tauri
// runtime, and WEDGE the renderer (no screenshot possible).
//
// Two things matter:
//  1) window.__TAURI_INTERNALS__.invoke must resolve (never reject) so providers don't
//     hang. Unknown commands return a render-safe default ([] for lists, {} for config).
//  2) The onboarding gate (src/app/layout.tsx): the ENTIRE app renders BLANK/onboarding
//     until get_onboarding_status reports a completed onboarding — so this always
//     returns a value with a model_status.parakeet field.
//
// URL params (consumed by the specs/0060 screenshot pipeline):
//   onboardingStep=1..5  — force the onboarding wizard to that step (omit for "done").
//   theme=deck|faceplate|dark|light — deck=dark, faceplate=light (product names for the
//     two themes); dark/light pass straight through. Written to the real
//     THEME_STORAGE_KEY (src/contexts/ThemeContext.tsx) before the app boots.
//   sidebar=open — expand the sidebar (default is collapsed). Written to the real
//     SIDEBAR_COLLAPSED_KEY (src/components/Sidebar/SidebarProvider.tsx).
(function () {
  const q = new URLSearchParams(location.search);

  const step = Number(q.get('onboardingStep') || 0);

  const THEME_STORAGE_KEY = 'nixon.theme';
  const themeParam = q.get('theme');
  const THEME_MAP = { deck: 'dark', faceplate: 'light', dark: 'dark', light: 'light' };
  if (themeParam && THEME_MAP[themeParam]) {
    localStorage.setItem(THEME_STORAGE_KEY, THEME_MAP[themeParam]);
  }

  const SIDEBAR_COLLAPSED_KEY = 'nixon.sidebar.collapsed';
  if (q.get('sidebar') === 'open') {
    localStorage.setItem(SIDEBAR_COLLAPSED_KEY, '0');
  }

  // --- Fixture dataset (src-tauri/fixtures/demo), embedded verbatim. ---
  const PEOPLE = ${JSON.stringify(people)};
  const MEETINGS = ${JSON.stringify(meetings)};

  const byId = (id) => MEETINGS.find((m) => m.id === id);
  const personById = (id) => PEOPLE.find((p) => p.id === id);

  // Re-bases fixture days_ago/time_of_day onto "now" so screenshots always show a
  // recent-looking dashboard, regardless of when they're taken (mirrors the dev-fixtures
  // seeder's own re-basing, src-tauri/src/dev_fixtures/dataset.rs).
  function dayStart(m) {
    const d = new Date();
    d.setDate(d.getDate() - m.days_ago);
    const [h, mi] = m.time_of_day.split(':').map(Number);
    d.setHours(h, mi, 0, 0);
    return d;
  }
  const meetingEnd = (m) => new Date(dayStart(m).getTime() + m.duration_seconds * 1000);

  // First non-heading, non-empty markdown line — a short glanceable snippet, matching
  // the intent of \`gist\` on the real Meeting DTO (src-tauri/src/meetings/view.rs).
  function gistFrom(markdown) {
    if (!markdown) return null;
    for (const raw of markdown.split('\\n')) {
      const line = raw.trim();
      if (!line || line.startsWith('#')) continue;
      return line.replace(/^[-*]\\s*/, '').replace(/\\*\\*/g, '').slice(0, 140);
    }
    return null;
  }

  function speakerDisplayName(m, key) {
    const s = (m.speakers || []).find((s) => s.key === key);
    return s ? s.display_name : null;
  }

  // Meeting (src-tauri/src/meetings/view.rs \`Meeting\`, #[serde(rename_all = "camelCase")]).
  // Used by api_get_meetings (src/app/meetings/page.tsx et al).
  function meetingRow(m, index) {
    const attendees = [
      { name: 'You', email: null, isCurrentUser: true },
      ...(m.participants || []).map((pid) => {
        const p = personById(pid);
        return { name: p ? p.display_name : pid, email: p ? p.email : null, isCurrentUser: false };
      }),
    ];
    return {
      id: m.id,
      title: m.title,
      createdAt: dayStart(m).toISOString(),
      updatedAt: dayStart(m).toISOString(),
      durationSeconds: m.duration_seconds,
      gist: gistFrom(m.summary_markdown) || gistFrom(m.notes_markdown),
      origin: 'recorded',
      calendarEventId: null,
      attendees,
      attendeeCount: attendees.length,
      reelNumber: index + 1,
    };
  }

  // MeetingMetadata (meetings/view.rs \`MeetingMetadata\` — NOT rename_all=camelCase;
  // only calendarEventId/calendarSeriesKey/reelNumber carry an explicit #[serde(rename)]).
  // Used by api_get_meeting_metadata (src/hooks/usePaginatedTranscripts.ts — the
  // meeting-details header/title source).
  function meetingMetadata(m, index) {
    return {
      id: m.id,
      title: m.title,
      created_at: dayStart(m).toISOString(),
      updated_at: dayStart(m).toISOString(),
      folder_path: null,
      origin: 'recorded',
      calendarEventId: null,
      calendarSeriesKey: null,
      reelNumber: index + 1,
    };
  }

  // MeetingTranscript (meetings/view.rs — no rename_all, fields are snake_case).
  function buildTranscripts(m) {
    return (m.segments || []).map((seg) => ({
      id: seg.id,
      text: seg.text,
      timestamp: new Date(dayStart(m).getTime() + seg.start * 1000).toLocaleTimeString(),
      audio_start_time: seg.start,
      audio_end_time: seg.end,
      duration: seg.end - seg.start,
      speaker: seg.speaker || null,
      speaker_name: seg.speaker ? speakerDisplayName(m, seg.speaker) : null,
    }));
  }

  // MeetingDetails (meetings/view.rs — no rename_all except calendarEventId).
  // Used by services/storageService.ts's getMeeting().
  function meetingDetails(m) {
    return {
      id: m.id,
      title: m.title,
      created_at: dayStart(m).toISOString(),
      updated_at: dayStart(m).toISOString(),
      origin: 'recorded',
      calendarEventId: null,
      transcripts: buildTranscripts(m),
    };
  }

  const FIXED_CREATED_AT = '2026-01-01T00:00:00.000Z';

  // Whether the on-disk models are "ready" for the onboardingStep being previewed:
  // no step param (0, i.e. onboarding already completed) or a step PAST the download
  // step (4/5) means ready; steps 1-3 preview onboarding still in progress, so the
  // models must read as not-yet-downloaded — consistent with ONBOARDING.model_status
  // below. Drives parakeet_has_available_models / builtin_ai_is_model_ready so
  // DownloadProgressStep (onboardingStep=3) shows the cards actually downloading
  // instead of already-completed.
  const MODELS_READY = step === 0 || step > 3;

  const ONBOARDING = step
    ? {
        version: '1.0',
        completed: false,
        current_step: step,
        model_status: {
          parakeet: step > 3 ? 'downloaded' : 'not_downloaded',
          summary: step > 3 ? 'downloaded' : 'not_downloaded',
          selected_summary_model: step > 3 ? 'qwen3.5:2b' : null,
        },
        last_updated: new Date().toISOString(),
      }
    : {
        version: '1.0',
        completed: true,
        current_step: 4,
        model_status: { parakeet: 'downloaded', summary: 'downloaded', selected_summary_model: 'qwen3.5:2b' },
        last_updated: new Date().toISOString(),
      };

  const FIXTURES = {
    // onboarding.rs \`get_onboarding_status\` -> Result<Option<OnboardingStatus>, String>.
    get_onboarding_status: () => ONBOARDING,

    // audio/recording_commands.rs \`get_recording_state\` -> serde_json::json!({...})
    // (snake_case keys, built by hand, no struct/rename_all).
    get_recording_state: () => ({
      is_recording: false,
      is_paused: false,
      is_active: false,
      recording_duration: 0,
      active_duration: 0,
      total_pause_duration: 0,
      current_pause_duration: 0,
    }),

    // notifications/os_commands.rs (specs/0068). The settings shot renders the
    // permission row, which asks these three before it can draw anything.
    notif_capability: () => ({ supported: true, reason: null }),
    notif_authorization_status: () => 'authorized',
    notif_deliver: () => undefined,

    // meetings/commands.rs \`api_get_meetings\` -> Vec<Meeting>.
    api_get_meetings: () => MEETINGS.map(meetingRow),

    // meetings/commands.rs \`api_get_meeting\` -> MeetingDetails. Args: { meetingId }.
    api_get_meeting: ({ meetingId }) => {
      const m = byId(meetingId);
      return m ? meetingDetails(m) : null;
    },

    // meetings/commands.rs \`api_get_meeting_metadata\` -> MeetingMetadata. Args: { meetingId }.
    // Not in the original command checklist, but usePaginatedTranscripts.ts (the
    // meeting-details transcript panel) calls it for the header/title — without it the
    // meeting-details page renders with no title.
    api_get_meeting_metadata: ({ meetingId }) => {
      const index = MEETINGS.findIndex((m) => m.id === meetingId);
      return index === -1 ? null : meetingMetadata(MEETINGS[index], index);
    },

    // meetings/commands.rs \`api_get_meeting_transcripts\` -> PaginatedTranscriptsResponse.
    // Args: { meetingId, limit, offset } (src/hooks/usePaginatedTranscripts.ts,
    // src/lib/fetch-all-transcripts.ts).
    api_get_meeting_transcripts: ({ meetingId, limit, offset }) => {
      const all = buildTranscripts(byId(meetingId) || {});
      const start = offset || 0;
      const end = limit ? start + limit : all.length;
      const page = all.slice(start, end);
      return { transcripts: page, total_count: all.length, has_more: end < all.length };
    },

    // diarization/commands.rs \`api_get_meeting_speakers\` -> Vec<SpeakerDto>
    // (#[serde(rename_all = "camelCase")]). Args: { meetingId }.
    api_get_meeting_speakers: ({ meetingId }) =>
      (byId(meetingId)?.speakers || []).map((s) => ({
        speakerKey: s.key,
        displayName: s.display_name,
        isLocal: !!s.is_local,
        email: null,
        personId: s.person_id || null,
      })),

    // summary/commands.rs \`api_get_summary\` -> SummaryResponse (meetingName is
    // #[serde(rename)]'d; meeting_id/start/end/data/error are not). Args: { meetingId }.
    api_get_summary: ({ meetingId }) => {
      const m = byId(meetingId);
      if (!m || !m.summary_markdown) {
        return { status: 'idle', meetingName: null, meeting_id: meetingId, start: null, end: null, data: null, error: null };
      }
      return {
        status: 'completed',
        meetingName: m.title,
        meeting_id: meetingId,
        start: dayStart(m).toISOString(),
        end: meetingEnd(m).toISOString(),
        data: { markdown: m.summary_markdown },
        error: null,
      };
    },

    // database/commands.rs \`api_get_meeting_notes\` -> Option<MeetingNote>
    // (#[serde(rename_all = "camelCase")]). Args: { meetingId }.
    api_get_meeting_notes: ({ meetingId }) => {
      const m = byId(meetingId);
      if (!m || !m.notes_markdown) return null;
      return {
        meetingId,
        notesMarkdown: m.notes_markdown,
        notesJson: null,
        enhancedMarkdown: null,
        enhancedJson: null,
        enhancedAt: null,
        enhancedModel: null,
        prepMarkdown: null,
      };
    },

    // people/commands.rs \`api_list_people\` / \`api_list_people_ranked\` -> Vec<Person>
    // (database/repositories/people.rs, #[serde(rename_all = "camelCase")]). No args.
    api_list_people: () => PEOPLE.map((p) => personDto(p)),
    api_list_people_ranked: () => PEOPLE.map((p) => personDto(p)),

    // people/commands.rs \`api_get_person\` -> Option<Person>. Arg is { id }, NOT
    // { personId } (src/lib/people.ts: invoke('api_get_person', { id })).
    api_get_person: ({ id }) => {
      const p = personById(id);
      return p ? personDto(p) : null;
    },

    // action_items/commands.rs \`api_get_action_items\` -> Vec<ActionItem>
    // (database/repositories/action_item.rs, #[serde(rename_all = "camelCase")]).
    // Per-meeting, not global: args { meetingId } (ActionItemsSection.tsx).
    api_get_action_items: ({ meetingId }) => {
      const m = byId(meetingId);
      if (!m) return [];
      const created = dayStart(m).toISOString();
      return (m.action_items || []).map((a, i) => ({
        id: 'ai-' + meetingId + '-' + i,
        meetingId,
        description: a.description,
        assigneePersonId: a.assignee && a.assignee !== 'self' ? a.assignee : null,
        assigneeIsSelf: a.assignee === 'self',
        assigneeRaw: null,
        dueHint: a.due_hint || null,
        dueDate: null,
        status: 'open',
        source: 'extracted',
        userEdited: false,
        contentKey: 'ck-' + meetingId + '-' + i,
        createdAt: created,
        updatedAt: created,
        completedAt: null,
        sortOrder: i,
      }));
    },

    // calendar/day_agenda.rs \`api_get_day_agenda\` -> Vec<DayAgendaItem>
    // (#[serde(rename_all = "camelCase")]). Today's recorded meetings (days_ago === 0).
    api_get_day_agenda: () =>
      MEETINGS.filter((m) => m.days_ago === 0).map((m) => ({
        id: m.id,
        title: m.title,
        startTime: dayStart(m).toISOString(),
        endTime: meetingEnd(m).toISOString(),
        source: 'recording',
        zoomUrl: null,
        attendees: [],
        attendeeCount: (m.participants || []).length,
        meetingId: m.id,
        status: {
          recorded: true,
          transcribed: (m.segments || []).length > 0,
          summarized: !!m.summary_markdown,
          speakersIdentified: (m.speakers || []).length > 0,
        },
        dismissed: false,
        dismissKey: m.id,
        seriesKey: null,
      })),

    // calendar/commands.rs \`api_get_calendar_access_status\` -> String. No args.
    api_get_calendar_access_status: () => 'authorized',

    // diarization/commands.rs \`api_diarization_status\` -> Option<DiarizationRunStatus>;
    // null means "no run this session" (src/hooks/useDiarization.ts). Args: { meetingId }.
    api_diarization_status: () => null,

    // meetings/commands.rs \`api_get_meeting_processing_mode\` -> Option<String>; null
    // means "no override, follow the global default". Args: { meetingId }.
    api_get_meeting_processing_mode: () => null,

    // audio/retention.rs \`api_meeting_audio_available\` -> bool. Args: { meetingId }.
    api_meeting_audio_available: () => true,

    // parakeet_engine/commands.rs \`parakeet_has_available_models\` -> bool. No args.
    // Tracks MODELS_READY (see above) so an in-progress onboardingStep preview (1-3)
    // shows the Parakeet card as not-yet-downloaded, not falsely completed.
    parakeet_has_available_models: () => MODELS_READY,

    // summary/summary_engine/commands.rs \`builtin_ai_is_model_ready\` -> bool.
    // Args: { modelName, refresh } (both ignored here). Tracks MODELS_READY, same
    // reasoning as parakeet_has_available_models above.
    builtin_ai_is_model_ready: () => MODELS_READY,

    // summary/summary_engine/commands.rs \`builtin_ai_get_recommended_model\` -> String.
    // No args. OnboardingContext falls back to this when no model is yet selected
    // (onboardingStep <= 3, where ONBOARDING.model_status.selected_summary_model is
    // null); without it, resolveOnboardingSummaryModelStatus
    // (src/lib/onboarding-summary-model.ts) built its "selected model" from the
    // fallback's [] and read that as ready, showing the summary card as already
    // downloaded during the step-3 preview.
    builtin_ai_get_recommended_model: () => 'qwen3.5:2b',

    // onboarding_disk.rs \`get_models_disk_check\` -> DiskCheck { free_bytes, required_bytes,
    // ok, models_dir }. Args: { summaryModel }. SetupOverviewStep (specs/0061 W1 Task 1)
    // calls this on mount to decide whether to show the "not enough free space" warning;
    // answering with plenty of free space keeps the onboarding-2 screenshot on its
    // happy path (no warning, "Let's Go" CTA) rather than the low-disk state.
    get_models_disk_check: () => ({
      free_bytes: 200 * 1024 * 1024 * 1024,
      required_bytes: (670 + 1221) * 1024 * 1024,
      ok: true,
      models_dir: '/tmp/nixon-demo/models',
    }),

    // parakeet_engine/commands.rs \`parakeet_download_model\` -> (). Args: { modelName }.
    // DownloadProgressStep starts this on mount whenever parakeetDownloaded is false
    // (i.e. during the onboardingStep 1-3 preview); answering it explicitly (rather
    // than relying on the array/object fallback) keeps the intent obvious here.
    parakeet_download_model: () => undefined,

    // summary/summary_engine/commands.rs \`builtin_ai_download_model\` -> (). Args:
    // { modelName }. Started the same way, for the summary model.
    builtin_ai_download_model: () => undefined,
  };

  // database/repositories/people.rs \`Person\` (#[serde(rename_all = "camelCase")]).
  function personDto(p) {
    return {
      id: p.id,
      email: p.email || null,
      displayName: p.display_name,
      role: p.role || null,
      notes: null,
      voiceprintOptOut: false,
      starred: false,
      createdAt: FIXED_CREATED_AT,
      updatedAt: FIXED_CREATED_AT,
      photoDataUri: null,
    };
  }

  // Render-safe default for any command not in FIXTURES (the vast majority of the ~300
  // commands in registry.rs — auth/settings/model-download/import commands the demo
  // screens either don't call or call best-effort with a try/catch around the result).
  // Object-shaped commands are detected by a whole underscore-separated WORD match
  // (not a bare substring test): a naive /mode/i.test(cmd) also matches "get_ollama_
  // models" (contains "mode" inside "models"), returning {} where ConfigContext.tsx
  // expects OllamaModel[] and later does modelList.map(...) — TypeError, blank
  // "Application error" page on every route (ConfigContext wraps the whole app).
  const OBJECT_SHAPED_WORDS = new Set(['config', 'status', 'state', 'settings', 'info', 'summary', 'mode']);
  function fallback(cmd) {
    const words = cmd.toLowerCase().split(/[^a-z]+/);
    return words.some((w) => OBJECT_SHAPED_WORDS.has(w)) ? {} : [];
  }

  // Commands that a RELEASE build genuinely does not have. The blanket resolve above is
  // right for the ~300 real ones, but a debug-only command must reject here or the shots
  // show UI the shipped app never has — the Developer settings tab probes \`dev_get_flags\`
  // exactly this way to decide whether it exists (specs/0066 W3).
  const DEBUG_ONLY = new Set(['dev_get_flags', 'dev_load_fixtures', 'dev_reset_onboarding']);

  window.__TAURI_INTERNALS__ = {
    invoke: (cmd, args) =>
      DEBUG_ONLY.has(cmd)
        ? Promise.reject(new Error(\`Command \${cmd} not found\`))
        : Promise.resolve(Object.hasOwn(FIXTURES, cmd) ? FIXTURES[cmd](args || {}) : fallback(cmd)),
    transformCallback: () => Math.floor(Math.random() * 1e9),
    convertFileSrc: (p) => p,
    metadata: { currentWindow: { label: 'main' }, currentWebview: { label: 'main' } },
  };
})();
`;

writeFileSync(join(here, 'tauri-mock.js'), body);
console.log('wrote tauri-mock.js:', meetings.length, 'meetings,', people.length, 'people');
