import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, it, expect } from 'vitest';

// specs/0059 Task 10 — the headless-Chrome screenshot mock (scripts/shots/tauri-mock.js)
// is GENERATED from the dev-fixtures dataset (scripts/shots/build-mock.mjs, reading
// src-tauri/fixtures/demo/). This test is the contract between the two: every Tauri
// command the mock answers must be a real, registered command
// (src-tauri/src/registry.rs) — a typo'd or renamed command name here would silently
// pass in the browser (the mock's own fallback would just kick in) while quietly
// answering nothing useful, so the screenshot pipeline would render an empty screen
// with no test failure to explain why.
const root = join(__dirname, '..', '..');
const registry = readFileSync(join(root, 'src-tauri', 'src', 'registry.rs'), 'utf8');
const mock = readFileSync(join(root, 'scripts', 'shots', 'tauri-mock.js'), 'utf8');

// Scope the "which commands does this mock answer" scan to the `FIXTURES` object
// literal's own body (between `const FIXTURES = {` and its closing `};`), not the
// whole file. The surrounding `window.__TAURI_INTERNALS__ = { invoke, transformCallback,
// convertFileSrc, metadata }` wiring sits at the same 4-space indentation and its keys
// are plain lowercase `key:` pairs too (`invoke:`, `metadata:`) — scanning the whole file
// would misread those as "answered commands" and fail the registry check for names that
// were never meant to be Tauri command names at all.
const fixturesStart = mock.indexOf('const FIXTURES = {');
const fixturesEnd = mock.indexOf('\n  };', fixturesStart);
expect(fixturesStart).toBeGreaterThan(-1);
expect(fixturesEnd).toBeGreaterThan(fixturesStart);
const fixturesBody = mock.slice(fixturesStart, fixturesEnd);

describe('screenshot mock ↔ command registry', () => {
  it('every command the mock answers is registered', () => {
    // Matches top-level FIXTURES keys (4-space indented, `snake_case_name:`). Nested
    // object literals inside a command's own return value (e.g. `model_status: {...}`)
    // are indented deeper (6+ spaces) and don't match.
    const answered = [...fixturesBody.matchAll(/^\s{4}([a-z_]+):\s/gm)].map((m) => m[1]);
    expect(answered.length).toBeGreaterThan(10);
    const missing = answered.filter((c) => !new RegExp(`::${c}\\b`).test(registry));
    expect(missing).toEqual([]);
  });

  it('is generated from the fixture dataset', () => {
    expect(mock).toMatch(/GENERATED by scripts\/shots\/build-mock\.mjs/);
    // 'demo-01' / 'Maya Okafor' come straight from src-tauri/fixtures/demo/ (people.json +
    // meetings/01-product-sync.json) — proof the mock's data is the real fixture dataset,
    // not hand-written sample rows.
    expect(mock).toContain('demo-01');
    expect(mock).toContain('Maya Okafor');
  });
});
