import { renderHook, act } from '@testing-library/react';
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { useSegmentDeepLink } from '@/hooks/useSegmentDeepLink';

// specs/0033 — deep-link lifecycle for `?segment=<transcriptId>`.
// Locks the state machine that makes ⌘K transcript hits reliable:
// - the pump actively pages the transcript until the target's page is loaded
//   (the on-screen IntersectionObserver only fetches on user scroll);
// - a stale id (regenerated by re-transcription) is abandoned silently, but the
//   URL param is still cleaned;
// - consume-then-clear means re-selecting the SAME hit is a fresh null→X param
//   transition that re-seeds the intent.

const seg = (id: string) => ({ id });

function baseProps(overrides: Record<string, unknown> = {}) {
    return {
        meetingId: 'meet-1',
        segmentParam: 'seg-target' as string | null,
        segments: [seg('seg-1'), seg('seg-2')],
        hasMore: true,
        isLoading: false,
        isLoadingMore: false,
        loadMore: vi.fn(),
        onClearParam: vi.fn(),
        ...overrides,
    };
}

beforeEach(() => {
    vi.useFakeTimers();
});

afterEach(() => {
    vi.useRealTimers();
});

describe('useSegmentDeepLink', () => {
    it('pumps loadMore when the target segment is not loaded, re-firing as pages land', () => {
        const props = baseProps();
        const { rerender } = renderHook((p) => useSegmentDeepLink(p), { initialProps: props });

        act(() => {
            vi.advanceTimersByTime(200);
        });
        expect(props.loadMore).toHaveBeenCalledTimes(1);

        // A page lands without the target — the pump fires again (effect re-runs on
        // the new segments array).
        rerender({ ...props, segments: [seg('seg-1'), seg('seg-2'), seg('seg-3')] });
        act(() => {
            vi.advanceTimersByTime(200);
        });
        expect(props.loadMore).toHaveBeenCalledTimes(2);
        expect(props.onClearParam).not.toHaveBeenCalled();
    });

    it('waits while a page is in flight instead of stacking loadMore calls', () => {
        const props = baseProps({ isLoadingMore: true });
        renderHook((p) => useSegmentDeepLink(p), { initialProps: props });
        act(() => {
            vi.advanceTimersByTime(500);
        });
        expect(props.loadMore).not.toHaveBeenCalled();
        expect(props.onClearParam).not.toHaveBeenCalled();
    });

    it('does not treat the initial load (empty segments, hasMore=false) as exhaustion', () => {
        const props = baseProps({ segments: [], hasMore: false, isLoading: true });
        const { result } = renderHook((p) => useSegmentDeepLink(p), { initialProps: props });
        act(() => {
            vi.advanceTimersByTime(500);
        });
        expect(props.onClearParam).not.toHaveBeenCalled();
        expect(result.current.pendingSegmentId).toBe('seg-target');
    });

    it('stops pumping once the target segment is loaded (the view scrolls & consumes)', () => {
        const props = baseProps({ segments: [seg('seg-1'), seg('seg-target')] });
        const { result } = renderHook((p) => useSegmentDeepLink(p), { initialProps: props });
        act(() => {
            vi.advanceTimersByTime(500);
        });
        expect(props.loadMore).not.toHaveBeenCalled();
        expect(result.current.pendingSegmentId).toBe('seg-target');
    });

    it('abandons a stale id when pagination is exhausted: silent no-op, URL cleaned', () => {
        const props = baseProps({ hasMore: false });
        const { result } = renderHook((p) => useSegmentDeepLink(p), { initialProps: props });
        expect(result.current.pendingSegmentId).toBeNull();
        expect(props.onClearParam).toHaveBeenCalledTimes(1);
        expect(props.loadMore).not.toHaveBeenCalled();
    });

    it('consume() clears the intent + param, and a fresh null→X transition re-seeds', () => {
        const props = baseProps();
        const { result, rerender } = renderHook((p) => useSegmentDeepLink(p), {
            initialProps: props,
        });
        expect(result.current.pendingSegmentId).toBe('seg-target');

        act(() => {
            result.current.consume();
        });
        expect(result.current.pendingSegmentId).toBeNull();
        expect(props.onClearParam).toHaveBeenCalledTimes(1);

        // The URL param is replaced away (consume-then-clear): the intent stays consumed.
        rerender({ ...props, segmentParam: null });
        expect(result.current.pendingSegmentId).toBeNull();

        // Re-selecting the SAME hit in ⌘K is now a real null→X transition — re-fires.
        rerender({ ...props, segmentParam: 'seg-target' });
        expect(result.current.pendingSegmentId).toBe('seg-target');
    });

    it('voids the pending intent when navigating to a different meeting', () => {
        const props = baseProps();
        const { result, rerender } = renderHook((p) => useSegmentDeepLink(p), {
            initialProps: props,
        });
        expect(result.current.pendingSegmentId).toBe('seg-target');

        rerender({ ...props, meetingId: 'meet-2', segmentParam: null });
        expect(result.current.pendingSegmentId).toBeNull();
    });
});
